### ISSUE TITLE
dataset question and "n_frames" means what?

### ISSUE THREAD

**Issue by fight-Cy** [cyanbx/Prompt-Singer#1]
1. In the dataset, the OpenSinger data in the 'processed manifests' does not correspond to the open-source dataset 'OpenSinger'. 2. When seeking 'n_frames': the length of the acoustic unit sequences, what is meant by 'acoustic unit'?maybe mel?

**Comment by cyanbx** [comment]
1. We use an internal version of opensinger without checking if it matches with the open-source version. But I think the open-source version should be a subset of the version we use (maybe with a little difference in the format of item names). You may try to remove the items that are not in the public version from the manifest, and I think that won’t have a big influence on model performance.

2. ‘acoustic units’ refers to the quantized audio representation from sound stream.

**Comment by fight-Cy** [comment]
So, when creating my own dataset, how do i obtain this ‘n_frames’?

**Comment by cyanbx** [comment]
There are two possible ways of doing this:
1. Use the soundstream to conduct compression over your whole dataset to get the exact length. This might be a little time-consuming considering the volume of your dataset and the GPU you use.
2. Simply dividing the length of the 16kHz raw audio wav by 320 to get the estimated length, where 320 is the downsampling rate of soundstream. This might cause length mismatch of 1 or 2 frames, but that shouldn't be a big problem.
